# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Deploy with Maven
      uses: simontunnat/action-maven-deploy@v1
      with:
       # Username that should be used to connect to the repository
       username: er3Nxf
       # Password that should be used to connect to the repository
       password: Tj7Wccbv6k
       # Repository that should be deployed to
       repository: https://repo.rdc.aliyun.com/repository/117163-snapshot-YaLcWB
       # The Maven goals to be executed
       maven-goals: deploy
       # Additional Maven command line arguments
       # maven-args: # optional
